'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class ContosoUniversityEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=ContosoUniversityEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Course() As DbSet(Of Course)
    Public Overridable Property Enrollment() As DbSet(Of Enrollment)
    Public Overridable Property Student() As DbSet(Of Student)

End Class
