'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Student
    Public Property StudentID As Integer
    Public Property LastName As String
    Public Property FirstMidName As String
    Public Property EnrollementDate As Date

    Public Overridable Property Enrollment As ICollection(Of Enrollment) = New HashSet(Of Enrollment)

End Class
